#!/bin/bash
# uDESK Milestone Checkpoint System v1.0.7.3
# Creates checkpoints for major development milestones

set -e

# Source dependencies
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/ucode-input.sh"

MILESTONE_DIR="$HOME/uDESK/uMEMORY/milestones"
CHECKPOINT_DIR="${MILESTONE_DIR}/checkpoints"

# Ensure directories exist
mkdir -p "${CHECKPOINT_DIR}"

# Milestone checkpoint creation
create_milestone_checkpoint() {
    local milestone_name="$1"
    local completion_percentage="$2"
    local timestamp=$(date -u +%Y%m%d_%H%M%S)
    local checkpoint_file="${CHECKPOINT_DIR}/${milestone_name}_${timestamp}.md"
    
    echo "🏁 Creating milestone checkpoint: ${milestone_name}"
    
    # Create checkpoint document
    cat > "${checkpoint_file}" << EOF
# Milestone Checkpoint: ${milestone_name}

**Created:** $(date)
**Completion:** ${completion_percentage}%
**Version:** v1.0.7.3

## Achievement Summary

### Completed TODOs
$(grep "✅.*COMPLETED" "${SCRIPT_DIR}/../uMEMORY/sandbox/workflows/EXPRESS-DEV-TODOS.md" | sed 's|^//||' | sed 's/^[[:space:]]*/- /')

### Progress Metrics
- **TODO Completion Rate:** ${completion_percentage}%
- **Milestone Status:** $(get_milestone_status "${milestone_name}")
- **Sprint Context:** Express Dev Mode Implementation

## Technical Achievements

### Auto-Assist System
- Context-aware development suggestions
- Integrated with workflow hierarchy
- Smart timing and frequency control
- Enhanced Express Mode integration

### TODO Tree Integration
- VSCode extension configured
- Color-coded progress indicators
- Numbered TODO tracking (TODO-001 through TODO-018)
- Visual workflow management

### Sprint Progress Tracking
- Real-time milestone monitoring
- Visual progress bars
- Weighted progress calculation
- Comprehensive status reporting

## Next Steps
$(get_next_milestone_actions "${milestone_name}")

---
*Generated by uDESK Milestone Checkpoint System*
EOF

    echo "✅ Checkpoint saved: ${checkpoint_file}"
    
    # Log the checkpoint
    echo "$(date): Milestone checkpoint created for ${milestone_name} (${completion_percentage}%)" >> "${MILESTONE_DIR}/checkpoint.log"
}

# Get milestone status
get_milestone_status() {
    local milestone="$1"
    case "${milestone}" in
        "Express Dev System")
            echo "Near completion - Sprint progress tracking finalizing"
            ;;
        "Workflow System")
            echo "Ready to begin - Foundation complete"
            ;;
        "CHEST Desktop")
            echo "Awaiting workflow completion"
            ;;
        "Infrastructure")
            echo "Final phase - deployment ready"
            ;;
        *)
            echo "Status unknown"
            ;;
    esac
}

# Get next actions for milestone
get_next_milestone_actions() {
    local milestone="$1"
    case "${milestone}" in
        "Express Dev System")
            echo "- Complete TODO-005 sprint progress tracking"
            echo "- Finalize Express Dev System milestone"
            echo "- Begin Workflow System implementation"
            ;;
        "Workflow System")
            echo "- Implement TODO-006: TODOs into uDESK variable system"
            echo "- Build unified workflow management commands"
            echo "- Create hierarchical workflow relationships"
            ;;
        *)
            echo "- Assess current progress"
            echo "- Plan next development phase"
            ;;
    esac
}

# Auto checkpoint on milestone completion
check_and_create_auto_checkpoint() {
    # Check Express Dev System milestone (TODO-001 through TODO-005)
    local express_completed=$(grep -E "TODO-00[1-5]:.*✅.*COMPLETED" "${SCRIPT_DIR}/../uMEMORY/sandbox/workflows/EXPRESS-DEV-TODOS.md" | wc -l | tr -d ' ')
    
    if [[ "$express_completed" == "5" ]]; then
        local checkpoint_exists=$(find "${CHECKPOINT_DIR}" -name "Express_Dev_System_*.md" | wc -l)
        if [[ "$checkpoint_exists" == "0" ]]; then
            create_milestone_checkpoint "Express_Dev_System" "100"
            echo ""
            echo "🎉 EXPRESS DEV SYSTEM MILESTONE COMPLETE!"
            echo "🏆 All 5 TODOs completed successfully"
            return 0
        fi
    elif [[ "$express_completed" == "4" ]]; then
        echo "📊 Express Dev System: 80% complete (4/5 TODOs)"
        echo "🎯 One more TODO to complete this milestone!"
    fi
    
    return 1
}

# Show milestone history
show_milestone_history() {
    echo "🏆 MILESTONE CHECKPOINT HISTORY"
    echo "════════════════════════════════"
    
    if [[ ! -d "${CHECKPOINT_DIR}" ]] || [[ -z "$(ls -A "${CHECKPOINT_DIR}" 2>/dev/null)" ]]; then
        echo "📝 No milestone checkpoints created yet"
        echo "💡 Complete a milestone to create the first checkpoint!"
        return
    fi
    
    local checkpoints=$(ls -t "${CHECKPOINT_DIR}"/*.md 2>/dev/null || echo "")
    
    if [[ -z "$checkpoints" ]]; then
        echo "📝 No milestone checkpoints found"
        return
    fi
    
    for checkpoint in $checkpoints; do
        local filename=$(basename "$checkpoint" .md)
        local milestone_name=$(echo "$filename" | sed 's/_[0-9]*_[0-9]*$//' | tr '_' ' ')
        local date_part=$(echo "$filename" | grep -o '[0-9]*_[0-9]*$' | tr '_' ' ')
        local formatted_date=$(echo "$date_part" | sed 's/\([0-9]\{4\}\)\([0-9]\{2\}\)\([0-9]\{2\}\) \([0-9]\{2\}\)\([0-9]\{2\}\)\([0-9]\{2\}\)/\1-\2-\3 \4:\5:\6/')
        
        echo "📋 ${milestone_name} - ${formatted_date}"
    done
}

# Main command interface
case "${1:-check}" in
    "create")
        milestone_name="$2"
        completion_percentage="$3"
        if [[ -z "$milestone_name" ]] || [[ -z "$completion_percentage" ]]; then
            prompt_text "Enter milestone name" milestone_name
            prompt_text "Enter completion percentage" completion_percentage
        fi
        create_milestone_checkpoint "$milestone_name" "$completion_percentage"
        ;;
    "check"|"auto")
        check_and_create_auto_checkpoint
        ;;
    "history"|"list")
        show_milestone_history
        ;;
    "help"|"--help")
        echo "🏁 uDESK Milestone Checkpoint Commands"
        echo "═══════════════════════════════════════"
        echo ""
        echo "Commands:"
        echo "  checkpoint create [name] [%]  # Create milestone checkpoint"
        echo "  checkpoint check              # Auto-check for completed milestones"
        echo "  checkpoint history            # Show checkpoint history"
        echo ""
        echo "Milestone checkpoints provide:"
        echo "• Progress documentation"
        echo "• Achievement tracking"
        echo "• Development history"
        echo "• Next steps planning"
        ;;
    *)
        echo "Unknown command: $1"
        echo "Use 'checkpoint help' for available commands"
        exit 1
        ;;
esac
