#!/bin/bash
echo "🚀 uDESK UTM Quick Start"
echo ""
echo "Everything is ready! Follow these steps:"
echo ""
echo "1. Open UTM"
echo "2. Create new Linux VM"
echo "3. Use TinyCore-current.iso as boot media"
echo "4. Set shared-folder as shared directory"
echo "5. Boot VM and run: ./auto-install-udesk.sh"
echo ""
echo "Files prepared:"
ls -la "$UTM_DIR"
echo ""
echo "Read UTM-INSTRUCTIONS.md for detailed steps"
